# Singular Value Decomposition (SVD)

SVD is one of the most general and fundamental forms of matrix factorization.

Every matrix has a *unique* decomposition in the following form:

$\underset{m \times n}M = 
    \underset{m \times r}U \times
    \underset{r \times r}\Sigma \times
    \underset{r \times n}V^T$

where
* $U$ is column orthogonal: $U^T U = I$
* $V$ is column orthogonal: $V^T V = I$
* $\Sigma$ is a diagonal matrix of positive values, where the diagonal is ordered in decreasing order.



## SVD for Movie Recommendations

We can use SVD to determine what we call ***latent features***. This will be best demonstrated with an example.

### Example

Let's look at users ratings of different movies. The ratings are from 1-5. 

|       | Matrix | Alien | StarWars | Casablanca | Titanic |
| ----- | ------ | ----- | -------- | ---------- | ------ |
| **Alice** |      1 |     2 |        2 |          - |      - |
|   **Bob** |      3 |     5 |        5 |          - |      - |
| **Cindy** |      4 |     4 |        4 |          - |      - |
|   **Dan** |      5 |     5 |        5 |          - |      - |
| **Emily** |      - |     2 |        - |          4 |      4 |
| **Frank** |      - |     - |        - |          5 |      5 |
|  **Greg** |      - |     1 |        - |          2 |      2 |
|  **Jose** |      5 |     - |        - |          - |      - |
| **Irfan** |      - |     - |        - |          - |      5 |
|**Yasaman**|      - |     4 |        - |          3 |      - |

It's reasonable to say that the first three users prefer science fiction, the next three prefer romance, and the last three have less defined tastes.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Matrix of movie ratings. Movies that haven't been watched get a value of 0.

In [2]:
M = np.array([[1, 2, 2, 0, 0],
              [3, 5, 5, 0, 0],
              [4, 4, 4, 0, 0],
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4],
              [0, 0, 0, 5, 5],
              [0, 1, 0, 2, 2],
              [5, 0, 0, 0, 0],
              [0, 0, 0, 0, 5],
              [0, 4, 0, 3, 0]])



In [10]:
# Compute SVD
from numpy.linalg import svd

U, sigma, VT = svd(M, full_matrices=False)

print U
print sigma
print VT

[[-0.20140271 -0.03433846  0.0878472  -0.13778436  0.06444606]
 [-0.52188486 -0.09388421  0.15618147 -0.28076897  0.13958354]
 [-0.47631775 -0.10082913 -0.07805177 -0.02080104  0.04276566]
 [-0.59539718 -0.12603641 -0.09756472 -0.0260013   0.05345708]
 [-0.14417552  0.53600138  0.09830452  0.08253916 -0.12250631]
 [-0.07026304  0.6567653  -0.13097949  0.13195446  0.59101499]
 [-0.07208776  0.26800069  0.04915226  0.04126958 -0.06125316]
 [-0.18378081 -0.0803805  -0.63436545  0.63691918 -0.21531614]
 [-0.0296344   0.35522756 -0.42538073 -0.57242473 -0.54732819]
 [-0.20030736  0.20210091  0.58281697  0.37657869 -0.5076307 ]]
[ 14.34933414  10.43761678   5.18848117   3.95376209   1.89741774]
[[-0.52742644 -0.63112022 -0.55016397 -0.11659878 -0.08504679]
 [-0.16779618  0.05526266 -0.15057044  0.62946708  0.74154583]
 [-0.65827864  0.52685944  0.03017667  0.30549905 -0.44141598]
 [ 0.50364539 -0.04551653 -0.47868945  0.55698956 -0.45264624]
 [-0.08170893 -0.56478376  0.66677877  0.43198251 

In [11]:
# Make interpretable
movies = ['Matrix','Alien','StarWars','Casablanca','Titanic']
users = ['Alice','Bob','Cindy','Dan','Emily','Frank','Greg', 'Jose', 'Irfan', 'Yasaman']

U, sigma, VT = (np.around(x,2) for x in (U,sigma,VT))

U = pd.DataFrame(U, index=users)
VT = pd.DataFrame(VT, columns=movies)

print U
print np.diag(sigma)
print VT


            0     1     2     3     4
Alice   -0.20 -0.03  0.09 -0.14  0.06
Bob     -0.52 -0.09  0.16 -0.28  0.14
Cindy   -0.48 -0.10 -0.08 -0.02  0.04
Dan     -0.60 -0.13 -0.10 -0.03  0.05
Emily   -0.14  0.54  0.10  0.08 -0.12
Frank   -0.07  0.66 -0.13  0.13  0.59
Greg    -0.07  0.27  0.05  0.04 -0.06
Jose    -0.18 -0.08 -0.63  0.64 -0.22
Irfan   -0.03  0.36 -0.43 -0.57 -0.55
Yasaman -0.20  0.20  0.58  0.38 -0.51
[[ 14.35   0.     0.     0.     0.  ]
 [  0.    10.44   0.     0.     0.  ]
 [  0.     0.     5.19   0.     0.  ]
 [  0.     0.     0.     3.95   0.  ]
 [  0.     0.     0.     0.     1.9 ]]
   Matrix  Alien  StarWars  Casablanca  Titanic
0   -0.53  -0.63     -0.55       -0.12    -0.09
1   -0.17   0.06     -0.15        0.63     0.74
2   -0.66   0.53      0.03        0.31    -0.44
3    0.50  -0.05     -0.48        0.56    -0.45
4   -0.08  -0.56      0.67        0.43    -0.21


In [12]:
# Power
# singular values are square roots of eigenvalues
total_power = np.sum(sigma**2)
print total_power

fraction_power = np.cumsum(sigma**2) / total_power
fraction_power

361.0647


array([ 0.57032022,  0.87218745,  0.94678932,  0.99000179,  1.        ])

In [13]:
# Keep only top two concepts
U = U.iloc[:,:2]
sigma = sigma[:2]
VT = VT.iloc[:2,:]

print U
print np.diag(sigma)
print VT

            0     1
Alice   -0.20 -0.03
Bob     -0.52 -0.09
Cindy   -0.48 -0.10
Dan     -0.60 -0.13
Emily   -0.14  0.54
Frank   -0.07  0.66
Greg    -0.07  0.27
Jose    -0.18 -0.08
Irfan   -0.03  0.36
Yasaman -0.20  0.20
[[ 14.35   0.  ]
 [  0.    10.44]]
   Matrix  Alien  StarWars  Casablanca  Titanic
0   -0.53  -0.63     -0.55       -0.12    -0.09
1   -0.17   0.06     -0.15        0.63     0.74


The matrices $U$ and $V$ can be used to estimate regularized distances between users and movies, respectively. As such, SVD can be thought of as a pre-processing step for other collaborative filtering algorithms

### Recommendations

In addition, the reconstructed matrix can be used can be used to make recommendations directly.

In [14]:
Mhat = np.around(U.dot(np.diag(sigma)).dot(VT),2)
Mhat

Matrix  Alien  StarWars  Casablanca  Titanic
Alice      1.57   1.79      1.63        0.15     0.03
Bob        4.11   4.64      4.25        0.30    -0.02
Cindy      3.83   4.28      3.94        0.17    -0.15
Dan        4.79   5.34      4.94        0.18    -0.23
Emily      0.11   1.60      0.26        3.79     4.35
Frank     -0.64   1.05     -0.48        4.46     5.19
Greg       0.05   0.80      0.13        1.90     2.18
Jose       1.51   1.58      1.55       -0.22    -0.39
Irfan     -0.41   0.50     -0.33        2.42     2.82
Yasaman    1.17   1.93      1.27        1.66     1.80

In [15]:
#What are Irfan's predicted ratings of all movies - which should he wath next?

Mhat.loc['Irfan'].sort_values(ascending=False)

Titanic       2.82
Casablanca    2.42
Alien         0.50
StarWars     -0.33
Matrix       -0.41
Name: Irfan, dtype: float64